package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BusinessResponseBase struct {
    // Name of the owner or primary person associated with the business.
    account_holder_name *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Incorporated address information for the business. Note: This field is required for payouts, deposits, or account-to-account transfers. Orum requires a physical address for all registered businesses; aligned with standards mandated by FinCEN and the FDIC. A physical address is a tangible building address, such as a home, office, or office suite. A PO Box is a mailing address, but not a physical address.
    addresses []PostalAddressResponseable
    // A trade name or pseudonym used by the business that is not its officially registered company name. Accepts alphanumeric characters and hyphens, dashes, periods, apostrophes, spaces, hashes, colons, forward slashes, and diacritics.
    business_name *string
    // Timestamp when the status of the resource was set to "closed".
    closed_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // List of contact information for the business.
    contacts []ContactResponseBusinessable
    // Timestamp when the resource was created.
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Unique reference id for the customer (business or person) resource. Generated by you.
    customer_reference_id *string
    // Describes the type of business entity.
    entity_type *string
    // Orum generated unique id for the resource.
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // Date the business was incorporated, in YYYY-MM-DD format.
    incorporation_date *string
    // The legal name of the business as it appears on official registration forms. Accepts alphanumeric characters and hyphens, dashes, periods, apostrophes, spaces, hashes, colons, forward slashes, and diacritics.
    legal_name *string
    // Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
    metadata BusinessResponseBase_metadataable
    // Status of Business.
    status *BusinessStatus
    // 9-digit corporate tax id of business - can be Taxpayer Identification Number (TIN) or Employer Identification Number (EIN). Note: This field is required for payouts, deposits, or account-to-account transfers.
    tax_id *string
    // The type of tax ID number associated with the business. Note: This field is required for payouts, deposits, or account-to-account transfers.
    tax_id_type *string
    // Timestamp when the resource was last updated.
    updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
}
// NewBusinessResponseBase instantiates a new BusinessResponseBase and sets the default values.
func NewBusinessResponseBase()(*BusinessResponseBase) {
    m := &BusinessResponseBase{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateBusinessResponseBaseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBusinessResponseBaseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBusinessResponseBase(), nil
}
// GetAccountHolderName gets the account_holder_name property value. Name of the owner or primary person associated with the business.
// returns a *string when successful
func (m *BusinessResponseBase) GetAccountHolderName()(*string) {
    return m.account_holder_name
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *BusinessResponseBase) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAddresses gets the addresses property value. Incorporated address information for the business. Note: This field is required for payouts, deposits, or account-to-account transfers. Orum requires a physical address for all registered businesses; aligned with standards mandated by FinCEN and the FDIC. A physical address is a tangible building address, such as a home, office, or office suite. A PO Box is a mailing address, but not a physical address.
// returns a []PostalAddressResponseable when successful
func (m *BusinessResponseBase) GetAddresses()([]PostalAddressResponseable) {
    return m.addresses
}
// GetBusinessName gets the business_name property value. A trade name or pseudonym used by the business that is not its officially registered company name. Accepts alphanumeric characters and hyphens, dashes, periods, apostrophes, spaces, hashes, colons, forward slashes, and diacritics.
// returns a *string when successful
func (m *BusinessResponseBase) GetBusinessName()(*string) {
    return m.business_name
}
// GetClosedAt gets the closed_at property value. Timestamp when the status of the resource was set to "closed".
// returns a *Time when successful
func (m *BusinessResponseBase) GetClosedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.closed_at
}
// GetContacts gets the contacts property value. List of contact information for the business.
// returns a []ContactResponseBusinessable when successful
func (m *BusinessResponseBase) GetContacts()([]ContactResponseBusinessable) {
    return m.contacts
}
// GetCreatedAt gets the created_at property value. Timestamp when the resource was created.
// returns a *Time when successful
func (m *BusinessResponseBase) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetCustomerReferenceId gets the customer_reference_id property value. Unique reference id for the customer (business or person) resource. Generated by you.
// returns a *string when successful
func (m *BusinessResponseBase) GetCustomerReferenceId()(*string) {
    return m.customer_reference_id
}
// GetEntityType gets the entity_type property value. Describes the type of business entity.
// returns a *string when successful
func (m *BusinessResponseBase) GetEntityType()(*string) {
    return m.entity_type
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BusinessResponseBase) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["account_holder_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccountHolderName(val)
        }
        return nil
    }
    res["addresses"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreatePostalAddressResponseFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]PostalAddressResponseable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(PostalAddressResponseable)
                }
            }
            m.SetAddresses(res)
        }
        return nil
    }
    res["business_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBusinessName(val)
        }
        return nil
    }
    res["closed_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClosedAt(val)
        }
        return nil
    }
    res["contacts"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateContactResponseBusinessFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ContactResponseBusinessable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ContactResponseBusinessable)
                }
            }
            m.SetContacts(res)
        }
        return nil
    }
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["customer_reference_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerReferenceId(val)
        }
        return nil
    }
    res["entity_type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEntityType(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["incorporation_date"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIncorporationDate(val)
        }
        return nil
    }
    res["legal_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLegalName(val)
        }
        return nil
    }
    res["metadata"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBusinessResponseBase_metadataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMetadata(val.(BusinessResponseBase_metadataable))
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseBusinessStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*BusinessStatus))
        }
        return nil
    }
    res["tax_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTaxId(val)
        }
        return nil
    }
    res["tax_id_type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTaxIdType(val)
        }
        return nil
    }
    res["updated_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. Orum generated unique id for the resource.
// returns a *UUID when successful
func (m *BusinessResponseBase) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetIncorporationDate gets the incorporation_date property value. Date the business was incorporated, in YYYY-MM-DD format.
// returns a *string when successful
func (m *BusinessResponseBase) GetIncorporationDate()(*string) {
    return m.incorporation_date
}
// GetLegalName gets the legal_name property value. The legal name of the business as it appears on official registration forms. Accepts alphanumeric characters and hyphens, dashes, periods, apostrophes, spaces, hashes, colons, forward slashes, and diacritics.
// returns a *string when successful
func (m *BusinessResponseBase) GetLegalName()(*string) {
    return m.legal_name
}
// GetMetadata gets the metadata property value. Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
// returns a BusinessResponseBase_metadataable when successful
func (m *BusinessResponseBase) GetMetadata()(BusinessResponseBase_metadataable) {
    return m.metadata
}
// GetStatus gets the status property value. Status of Business.
// returns a *BusinessStatus when successful
func (m *BusinessResponseBase) GetStatus()(*BusinessStatus) {
    return m.status
}
// GetTaxId gets the tax_id property value. 9-digit corporate tax id of business - can be Taxpayer Identification Number (TIN) or Employer Identification Number (EIN). Note: This field is required for payouts, deposits, or account-to-account transfers.
// returns a *string when successful
func (m *BusinessResponseBase) GetTaxId()(*string) {
    return m.tax_id
}
// GetTaxIdType gets the tax_id_type property value. The type of tax ID number associated with the business. Note: This field is required for payouts, deposits, or account-to-account transfers.
// returns a *string when successful
func (m *BusinessResponseBase) GetTaxIdType()(*string) {
    return m.tax_id_type
}
// GetUpdatedAt gets the updated_at property value. Timestamp when the resource was last updated.
// returns a *Time when successful
func (m *BusinessResponseBase) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updated_at
}
// Serialize serializes information the current object
func (m *BusinessResponseBase) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("account_holder_name", m.GetAccountHolderName())
        if err != nil {
            return err
        }
    }
    if m.GetAddresses() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetAddresses()))
        for i, v := range m.GetAddresses() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("addresses", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("business_name", m.GetBusinessName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("closed_at", m.GetClosedAt())
        if err != nil {
            return err
        }
    }
    if m.GetContacts() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetContacts()))
        for i, v := range m.GetContacts() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("contacts", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("created_at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("customer_reference_id", m.GetCustomerReferenceId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("entity_type", m.GetEntityType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("incorporation_date", m.GetIncorporationDate())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("legal_name", m.GetLegalName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("metadata", m.GetMetadata())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("tax_id", m.GetTaxId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("tax_id_type", m.GetTaxIdType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("updated_at", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAccountHolderName sets the account_holder_name property value. Name of the owner or primary person associated with the business.
func (m *BusinessResponseBase) SetAccountHolderName(value *string)() {
    m.account_holder_name = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *BusinessResponseBase) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAddresses sets the addresses property value. Incorporated address information for the business. Note: This field is required for payouts, deposits, or account-to-account transfers. Orum requires a physical address for all registered businesses; aligned with standards mandated by FinCEN and the FDIC. A physical address is a tangible building address, such as a home, office, or office suite. A PO Box is a mailing address, but not a physical address.
func (m *BusinessResponseBase) SetAddresses(value []PostalAddressResponseable)() {
    m.addresses = value
}
// SetBusinessName sets the business_name property value. A trade name or pseudonym used by the business that is not its officially registered company name. Accepts alphanumeric characters and hyphens, dashes, periods, apostrophes, spaces, hashes, colons, forward slashes, and diacritics.
func (m *BusinessResponseBase) SetBusinessName(value *string)() {
    m.business_name = value
}
// SetClosedAt sets the closed_at property value. Timestamp when the status of the resource was set to "closed".
func (m *BusinessResponseBase) SetClosedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.closed_at = value
}
// SetContacts sets the contacts property value. List of contact information for the business.
func (m *BusinessResponseBase) SetContacts(value []ContactResponseBusinessable)() {
    m.contacts = value
}
// SetCreatedAt sets the created_at property value. Timestamp when the resource was created.
func (m *BusinessResponseBase) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetCustomerReferenceId sets the customer_reference_id property value. Unique reference id for the customer (business or person) resource. Generated by you.
func (m *BusinessResponseBase) SetCustomerReferenceId(value *string)() {
    m.customer_reference_id = value
}
// SetEntityType sets the entity_type property value. Describes the type of business entity.
func (m *BusinessResponseBase) SetEntityType(value *string)() {
    m.entity_type = value
}
// SetId sets the id property value. Orum generated unique id for the resource.
func (m *BusinessResponseBase) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetIncorporationDate sets the incorporation_date property value. Date the business was incorporated, in YYYY-MM-DD format.
func (m *BusinessResponseBase) SetIncorporationDate(value *string)() {
    m.incorporation_date = value
}
// SetLegalName sets the legal_name property value. The legal name of the business as it appears on official registration forms. Accepts alphanumeric characters and hyphens, dashes, periods, apostrophes, spaces, hashes, colons, forward slashes, and diacritics.
func (m *BusinessResponseBase) SetLegalName(value *string)() {
    m.legal_name = value
}
// SetMetadata sets the metadata property value. Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
func (m *BusinessResponseBase) SetMetadata(value BusinessResponseBase_metadataable)() {
    m.metadata = value
}
// SetStatus sets the status property value. Status of Business.
func (m *BusinessResponseBase) SetStatus(value *BusinessStatus)() {
    m.status = value
}
// SetTaxId sets the tax_id property value. 9-digit corporate tax id of business - can be Taxpayer Identification Number (TIN) or Employer Identification Number (EIN). Note: This field is required for payouts, deposits, or account-to-account transfers.
func (m *BusinessResponseBase) SetTaxId(value *string)() {
    m.tax_id = value
}
// SetTaxIdType sets the tax_id_type property value. The type of tax ID number associated with the business. Note: This field is required for payouts, deposits, or account-to-account transfers.
func (m *BusinessResponseBase) SetTaxIdType(value *string)() {
    m.tax_id_type = value
}
// SetUpdatedAt sets the updated_at property value. Timestamp when the resource was last updated.
func (m *BusinessResponseBase) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updated_at = value
}
type BusinessResponseBaseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccountHolderName()(*string)
    GetAddresses()([]PostalAddressResponseable)
    GetBusinessName()(*string)
    GetClosedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetContacts()([]ContactResponseBusinessable)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCustomerReferenceId()(*string)
    GetEntityType()(*string)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetIncorporationDate()(*string)
    GetLegalName()(*string)
    GetMetadata()(BusinessResponseBase_metadataable)
    GetStatus()(*BusinessStatus)
    GetTaxId()(*string)
    GetTaxIdType()(*string)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    SetAccountHolderName(value *string)()
    SetAddresses(value []PostalAddressResponseable)()
    SetBusinessName(value *string)()
    SetClosedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetContacts(value []ContactResponseBusinessable)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCustomerReferenceId(value *string)()
    SetEntityType(value *string)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetIncorporationDate(value *string)()
    SetLegalName(value *string)()
    SetMetadata(value BusinessResponseBase_metadataable)()
    SetStatus(value *BusinessStatus)()
    SetTaxId(value *string)()
    SetTaxIdType(value *string)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
}
