package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CardResponseBase struct {
    // The account_holder_name property
    account_holder_name CardResponseBase_CardResponseBase_account_holder_nameable
    // The account_reference_id property
    account_reference_id *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The address property
    address CardResponseBase_CardResponseBase_addressable
    // Timestamp when the resource was created.
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Unique reference id for the customer (business or person) resource. Generated by you.
    customer_reference_id *string
    // The customer_resource_type property
    customer_resource_type *EndCustomerResourceType
    // The month in which the card expires.
    expiration_month *int32
    // The year in which the card expires.
    expiration_year *int32
    // Orum generated unique id for the resource.
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The last four digits of the card number supplied by the customer.
    last4 *string
    // Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
    metadata CardResponseBase_metadataable
    // Status of card in Orum system.
    status *CardStatus
    // Timestamp when the resource was last updated.
    updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
}
// CardResponseBase_CardResponseBase_account_holder_name composed type wrapper for classes CardAccountHolderNameBusinessable, CardAccountHolderNamePersonable
type CardResponseBase_CardResponseBase_account_holder_name struct {
    // Composed type representation for type CardAccountHolderNameBusinessable
    cardAccountHolderNameBusiness CardAccountHolderNameBusinessable
    // Composed type representation for type CardAccountHolderNamePersonable
    cardAccountHolderNamePerson CardAccountHolderNamePersonable
}
// NewCardResponseBase_CardResponseBase_account_holder_name instantiates a new CardResponseBase_CardResponseBase_account_holder_name and sets the default values.
func NewCardResponseBase_CardResponseBase_account_holder_name()(*CardResponseBase_CardResponseBase_account_holder_name) {
    m := &CardResponseBase_CardResponseBase_account_holder_name{
    }
    return m
}
// CreateCardResponseBase_CardResponseBase_account_holder_nameFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCardResponseBase_CardResponseBase_account_holder_nameFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCardResponseBase_CardResponseBase_account_holder_name()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
            }
        }
    }
    return result, nil
}
// GetCardAccountHolderNameBusiness gets the CardAccountHolderNameBusiness property value. Composed type representation for type CardAccountHolderNameBusinessable
// returns a CardAccountHolderNameBusinessable when successful
func (m *CardResponseBase_CardResponseBase_account_holder_name) GetCardAccountHolderNameBusiness()(CardAccountHolderNameBusinessable) {
    return m.cardAccountHolderNameBusiness
}
// GetCardAccountHolderNamePerson gets the CardAccountHolderNamePerson property value. Composed type representation for type CardAccountHolderNamePersonable
// returns a CardAccountHolderNamePersonable when successful
func (m *CardResponseBase_CardResponseBase_account_holder_name) GetCardAccountHolderNamePerson()(CardAccountHolderNamePersonable) {
    return m.cardAccountHolderNamePerson
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CardResponseBase_CardResponseBase_account_holder_name) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetCardAccountHolderNameBusiness() != nil {
        return m.GetCardAccountHolderNameBusiness().GetFieldDeserializers()
    } else if m.GetCardAccountHolderNamePerson() != nil {
        return m.GetCardAccountHolderNamePerson().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CardResponseBase_CardResponseBase_account_holder_name) GetIsComposedType()(bool) {
    return true
}
// Serialize serializes information the current object
func (m *CardResponseBase_CardResponseBase_account_holder_name) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetCardAccountHolderNameBusiness() != nil {
        err := writer.WriteObjectValue("", m.GetCardAccountHolderNameBusiness())
        if err != nil {
            return err
        }
    } else if m.GetCardAccountHolderNamePerson() != nil {
        err := writer.WriteObjectValue("", m.GetCardAccountHolderNamePerson())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCardAccountHolderNameBusiness sets the CardAccountHolderNameBusiness property value. Composed type representation for type CardAccountHolderNameBusinessable
func (m *CardResponseBase_CardResponseBase_account_holder_name) SetCardAccountHolderNameBusiness(value CardAccountHolderNameBusinessable)() {
    m.cardAccountHolderNameBusiness = value
}
// SetCardAccountHolderNamePerson sets the CardAccountHolderNamePerson property value. Composed type representation for type CardAccountHolderNamePersonable
func (m *CardResponseBase_CardResponseBase_account_holder_name) SetCardAccountHolderNamePerson(value CardAccountHolderNamePersonable)() {
    m.cardAccountHolderNamePerson = value
}
// CardResponseBase_CardResponseBase_address composed type wrapper for classes CardFullAddressable, CardZipOnlyAddressable
type CardResponseBase_CardResponseBase_address struct {
    // Composed type representation for type CardFullAddressable
    cardFullAddress CardFullAddressable
    // Composed type representation for type CardZipOnlyAddressable
    cardZipOnlyAddress CardZipOnlyAddressable
}
// NewCardResponseBase_CardResponseBase_address instantiates a new CardResponseBase_CardResponseBase_address and sets the default values.
func NewCardResponseBase_CardResponseBase_address()(*CardResponseBase_CardResponseBase_address) {
    m := &CardResponseBase_CardResponseBase_address{
    }
    return m
}
// CreateCardResponseBase_CardResponseBase_addressFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCardResponseBase_CardResponseBase_addressFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewCardResponseBase_CardResponseBase_address()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
            }
        }
    }
    return result, nil
}
// GetCardFullAddress gets the CardFullAddress property value. Composed type representation for type CardFullAddressable
// returns a CardFullAddressable when successful
func (m *CardResponseBase_CardResponseBase_address) GetCardFullAddress()(CardFullAddressable) {
    return m.cardFullAddress
}
// GetCardZipOnlyAddress gets the CardZipOnlyAddress property value. Composed type representation for type CardZipOnlyAddressable
// returns a CardZipOnlyAddressable when successful
func (m *CardResponseBase_CardResponseBase_address) GetCardZipOnlyAddress()(CardZipOnlyAddressable) {
    return m.cardZipOnlyAddress
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CardResponseBase_CardResponseBase_address) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetCardFullAddress() != nil {
        return m.GetCardFullAddress().GetFieldDeserializers()
    } else if m.GetCardZipOnlyAddress() != nil {
        return m.GetCardZipOnlyAddress().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *CardResponseBase_CardResponseBase_address) GetIsComposedType()(bool) {
    return true
}
// Serialize serializes information the current object
func (m *CardResponseBase_CardResponseBase_address) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetCardFullAddress() != nil {
        err := writer.WriteObjectValue("", m.GetCardFullAddress())
        if err != nil {
            return err
        }
    } else if m.GetCardZipOnlyAddress() != nil {
        err := writer.WriteObjectValue("", m.GetCardZipOnlyAddress())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCardFullAddress sets the CardFullAddress property value. Composed type representation for type CardFullAddressable
func (m *CardResponseBase_CardResponseBase_address) SetCardFullAddress(value CardFullAddressable)() {
    m.cardFullAddress = value
}
// SetCardZipOnlyAddress sets the CardZipOnlyAddress property value. Composed type representation for type CardZipOnlyAddressable
func (m *CardResponseBase_CardResponseBase_address) SetCardZipOnlyAddress(value CardZipOnlyAddressable)() {
    m.cardZipOnlyAddress = value
}
type CardResponseBase_CardResponseBase_account_holder_nameable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCardAccountHolderNameBusiness()(CardAccountHolderNameBusinessable)
    GetCardAccountHolderNamePerson()(CardAccountHolderNamePersonable)
    SetCardAccountHolderNameBusiness(value CardAccountHolderNameBusinessable)()
    SetCardAccountHolderNamePerson(value CardAccountHolderNamePersonable)()
}
type CardResponseBase_CardResponseBase_addressable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCardFullAddress()(CardFullAddressable)
    GetCardZipOnlyAddress()(CardZipOnlyAddressable)
    SetCardFullAddress(value CardFullAddressable)()
    SetCardZipOnlyAddress(value CardZipOnlyAddressable)()
}
// NewCardResponseBase instantiates a new CardResponseBase and sets the default values.
func NewCardResponseBase()(*CardResponseBase) {
    m := &CardResponseBase{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCardResponseBaseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCardResponseBaseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCardResponseBase(), nil
}
// GetAccountHolderName gets the account_holder_name property value. The account_holder_name property
// returns a CardResponseBase_CardResponseBase_account_holder_nameable when successful
func (m *CardResponseBase) GetAccountHolderName()(CardResponseBase_CardResponseBase_account_holder_nameable) {
    return m.account_holder_name
}
// GetAccountReferenceId gets the account_reference_id property value. The account_reference_id property
// returns a *string when successful
func (m *CardResponseBase) GetAccountReferenceId()(*string) {
    return m.account_reference_id
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CardResponseBase) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAddress gets the address property value. The address property
// returns a CardResponseBase_CardResponseBase_addressable when successful
func (m *CardResponseBase) GetAddress()(CardResponseBase_CardResponseBase_addressable) {
    return m.address
}
// GetCreatedAt gets the created_at property value. Timestamp when the resource was created.
// returns a *Time when successful
func (m *CardResponseBase) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetCustomerReferenceId gets the customer_reference_id property value. Unique reference id for the customer (business or person) resource. Generated by you.
// returns a *string when successful
func (m *CardResponseBase) GetCustomerReferenceId()(*string) {
    return m.customer_reference_id
}
// GetCustomerResourceType gets the customer_resource_type property value. The customer_resource_type property
// returns a *EndCustomerResourceType when successful
func (m *CardResponseBase) GetCustomerResourceType()(*EndCustomerResourceType) {
    return m.customer_resource_type
}
// GetExpirationMonth gets the expiration_month property value. The month in which the card expires.
// returns a *int32 when successful
func (m *CardResponseBase) GetExpirationMonth()(*int32) {
    return m.expiration_month
}
// GetExpirationYear gets the expiration_year property value. The year in which the card expires.
// returns a *int32 when successful
func (m *CardResponseBase) GetExpirationYear()(*int32) {
    return m.expiration_year
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CardResponseBase) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["account_holder_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCardResponseBase_CardResponseBase_account_holder_nameFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccountHolderName(val.(CardResponseBase_CardResponseBase_account_holder_nameable))
        }
        return nil
    }
    res["account_reference_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccountReferenceId(val)
        }
        return nil
    }
    res["address"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCardResponseBase_CardResponseBase_addressFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAddress(val.(CardResponseBase_CardResponseBase_addressable))
        }
        return nil
    }
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["customer_reference_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerReferenceId(val)
        }
        return nil
    }
    res["customer_resource_type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseEndCustomerResourceType)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerResourceType(val.(*EndCustomerResourceType))
        }
        return nil
    }
    res["expiration_month"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExpirationMonth(val)
        }
        return nil
    }
    res["expiration_year"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExpirationYear(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["last4"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLast4(val)
        }
        return nil
    }
    res["metadata"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateCardResponseBase_metadataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMetadata(val.(CardResponseBase_metadataable))
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseCardStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*CardStatus))
        }
        return nil
    }
    res["updated_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. Orum generated unique id for the resource.
// returns a *UUID when successful
func (m *CardResponseBase) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetLast4 gets the last4 property value. The last four digits of the card number supplied by the customer.
// returns a *string when successful
func (m *CardResponseBase) GetLast4()(*string) {
    return m.last4
}
// GetMetadata gets the metadata property value. Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
// returns a CardResponseBase_metadataable when successful
func (m *CardResponseBase) GetMetadata()(CardResponseBase_metadataable) {
    return m.metadata
}
// GetStatus gets the status property value. Status of card in Orum system.
// returns a *CardStatus when successful
func (m *CardResponseBase) GetStatus()(*CardStatus) {
    return m.status
}
// GetUpdatedAt gets the updated_at property value. Timestamp when the resource was last updated.
// returns a *Time when successful
func (m *CardResponseBase) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updated_at
}
// Serialize serializes information the current object
func (m *CardResponseBase) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("account_holder_name", m.GetAccountHolderName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("account_reference_id", m.GetAccountReferenceId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("address", m.GetAddress())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("created_at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("customer_reference_id", m.GetCustomerReferenceId())
        if err != nil {
            return err
        }
    }
    if m.GetCustomerResourceType() != nil {
        cast := (*m.GetCustomerResourceType()).String()
        err := writer.WriteStringValue("customer_resource_type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("expiration_month", m.GetExpirationMonth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("expiration_year", m.GetExpirationYear())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("last4", m.GetLast4())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("metadata", m.GetMetadata())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("updated_at", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAccountHolderName sets the account_holder_name property value. The account_holder_name property
func (m *CardResponseBase) SetAccountHolderName(value CardResponseBase_CardResponseBase_account_holder_nameable)() {
    m.account_holder_name = value
}
// SetAccountReferenceId sets the account_reference_id property value. The account_reference_id property
func (m *CardResponseBase) SetAccountReferenceId(value *string)() {
    m.account_reference_id = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CardResponseBase) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAddress sets the address property value. The address property
func (m *CardResponseBase) SetAddress(value CardResponseBase_CardResponseBase_addressable)() {
    m.address = value
}
// SetCreatedAt sets the created_at property value. Timestamp when the resource was created.
func (m *CardResponseBase) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetCustomerReferenceId sets the customer_reference_id property value. Unique reference id for the customer (business or person) resource. Generated by you.
func (m *CardResponseBase) SetCustomerReferenceId(value *string)() {
    m.customer_reference_id = value
}
// SetCustomerResourceType sets the customer_resource_type property value. The customer_resource_type property
func (m *CardResponseBase) SetCustomerResourceType(value *EndCustomerResourceType)() {
    m.customer_resource_type = value
}
// SetExpirationMonth sets the expiration_month property value. The month in which the card expires.
func (m *CardResponseBase) SetExpirationMonth(value *int32)() {
    m.expiration_month = value
}
// SetExpirationYear sets the expiration_year property value. The year in which the card expires.
func (m *CardResponseBase) SetExpirationYear(value *int32)() {
    m.expiration_year = value
}
// SetId sets the id property value. Orum generated unique id for the resource.
func (m *CardResponseBase) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetLast4 sets the last4 property value. The last four digits of the card number supplied by the customer.
func (m *CardResponseBase) SetLast4(value *string)() {
    m.last4 = value
}
// SetMetadata sets the metadata property value. Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
func (m *CardResponseBase) SetMetadata(value CardResponseBase_metadataable)() {
    m.metadata = value
}
// SetStatus sets the status property value. Status of card in Orum system.
func (m *CardResponseBase) SetStatus(value *CardStatus)() {
    m.status = value
}
// SetUpdatedAt sets the updated_at property value. Timestamp when the resource was last updated.
func (m *CardResponseBase) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updated_at = value
}
type CardResponseBaseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccountHolderName()(CardResponseBase_CardResponseBase_account_holder_nameable)
    GetAccountReferenceId()(*string)
    GetAddress()(CardResponseBase_CardResponseBase_addressable)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCustomerReferenceId()(*string)
    GetCustomerResourceType()(*EndCustomerResourceType)
    GetExpirationMonth()(*int32)
    GetExpirationYear()(*int32)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetLast4()(*string)
    GetMetadata()(CardResponseBase_metadataable)
    GetStatus()(*CardStatus)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    SetAccountHolderName(value CardResponseBase_CardResponseBase_account_holder_nameable)()
    SetAccountReferenceId(value *string)()
    SetAddress(value CardResponseBase_CardResponseBase_addressable)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCustomerReferenceId(value *string)()
    SetCustomerResourceType(value *EndCustomerResourceType)()
    SetExpirationMonth(value *int32)()
    SetExpirationYear(value *int32)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetLast4(value *string)()
    SetMetadata(value CardResponseBase_metadataable)()
    SetStatus(value *CardStatus)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
}
