package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PersonResponseBase struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Address information for the person. Note: This field is required for payouts, deposits, or account-to-account transfers.
    addresses []PostalAddressResponseable
    // Timestamp when the status of the resource was set to "closed".
    closed_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // List of contact information for the person.
    contacts []ContactResponsePersonable
    // Timestamp when the resource was created.
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Unique reference id for the customer (business or person) resource. Generated by you.
    customer_reference_id *string
    // Date of birth in YYYY-MM-DD format. Note: This field is required for payouts, deposits, or account-to-account transfers. Age must be less than 100 years and greater than 18 years to be verified.
    date_of_birth *string
    // The first_name property
    first_name *string
    // Orum generated unique id for the resource.
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The last_name property
    last_name *string
    // Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
    metadata PersonResponseBase_metadataable
    // The middle_name property
    middle_name *string
    // Status of person in Orum system.
    status *PersonStatus
    // Array that explains why the person failed verification.
    status_reasons []PersonReasonCodeable
    // Timestamp when the resource was last updated.
    updated_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
}
// NewPersonResponseBase instantiates a new PersonResponseBase and sets the default values.
func NewPersonResponseBase()(*PersonResponseBase) {
    m := &PersonResponseBase{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePersonResponseBaseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePersonResponseBaseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPersonResponseBase(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PersonResponseBase) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAddresses gets the addresses property value. Address information for the person. Note: This field is required for payouts, deposits, or account-to-account transfers.
// returns a []PostalAddressResponseable when successful
func (m *PersonResponseBase) GetAddresses()([]PostalAddressResponseable) {
    return m.addresses
}
// GetClosedAt gets the closed_at property value. Timestamp when the status of the resource was set to "closed".
// returns a *Time when successful
func (m *PersonResponseBase) GetClosedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.closed_at
}
// GetContacts gets the contacts property value. List of contact information for the person.
// returns a []ContactResponsePersonable when successful
func (m *PersonResponseBase) GetContacts()([]ContactResponsePersonable) {
    return m.contacts
}
// GetCreatedAt gets the created_at property value. Timestamp when the resource was created.
// returns a *Time when successful
func (m *PersonResponseBase) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetCustomerReferenceId gets the customer_reference_id property value. Unique reference id for the customer (business or person) resource. Generated by you.
// returns a *string when successful
func (m *PersonResponseBase) GetCustomerReferenceId()(*string) {
    return m.customer_reference_id
}
// GetDateOfBirth gets the date_of_birth property value. Date of birth in YYYY-MM-DD format. Note: This field is required for payouts, deposits, or account-to-account transfers. Age must be less than 100 years and greater than 18 years to be verified.
// returns a *string when successful
func (m *PersonResponseBase) GetDateOfBirth()(*string) {
    return m.date_of_birth
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PersonResponseBase) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["addresses"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreatePostalAddressResponseFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]PostalAddressResponseable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(PostalAddressResponseable)
                }
            }
            m.SetAddresses(res)
        }
        return nil
    }
    res["closed_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClosedAt(val)
        }
        return nil
    }
    res["contacts"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateContactResponsePersonFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ContactResponsePersonable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ContactResponsePersonable)
                }
            }
            m.SetContacts(res)
        }
        return nil
    }
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["customer_reference_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCustomerReferenceId(val)
        }
        return nil
    }
    res["date_of_birth"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDateOfBirth(val)
        }
        return nil
    }
    res["first_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFirstName(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["last_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastName(val)
        }
        return nil
    }
    res["metadata"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePersonResponseBase_metadataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMetadata(val.(PersonResponseBase_metadataable))
        }
        return nil
    }
    res["middle_name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMiddleName(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePersonStatus)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*PersonStatus))
        }
        return nil
    }
    res["status_reasons"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreatePersonReasonCodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]PersonReasonCodeable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(PersonReasonCodeable)
                }
            }
            m.SetStatusReasons(res)
        }
        return nil
    }
    res["updated_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    return res
}
// GetFirstName gets the first_name property value. The first_name property
// returns a *string when successful
func (m *PersonResponseBase) GetFirstName()(*string) {
    return m.first_name
}
// GetId gets the id property value. Orum generated unique id for the resource.
// returns a *UUID when successful
func (m *PersonResponseBase) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetLastName gets the last_name property value. The last_name property
// returns a *string when successful
func (m *PersonResponseBase) GetLastName()(*string) {
    return m.last_name
}
// GetMetadata gets the metadata property value. Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
// returns a PersonResponseBase_metadataable when successful
func (m *PersonResponseBase) GetMetadata()(PersonResponseBase_metadataable) {
    return m.metadata
}
// GetMiddleName gets the middle_name property value. The middle_name property
// returns a *string when successful
func (m *PersonResponseBase) GetMiddleName()(*string) {
    return m.middle_name
}
// GetStatus gets the status property value. Status of person in Orum system.
// returns a *PersonStatus when successful
func (m *PersonResponseBase) GetStatus()(*PersonStatus) {
    return m.status
}
// GetStatusReasons gets the status_reasons property value. Array that explains why the person failed verification.
// returns a []PersonReasonCodeable when successful
func (m *PersonResponseBase) GetStatusReasons()([]PersonReasonCodeable) {
    return m.status_reasons
}
// GetUpdatedAt gets the updated_at property value. Timestamp when the resource was last updated.
// returns a *Time when successful
func (m *PersonResponseBase) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updated_at
}
// Serialize serializes information the current object
func (m *PersonResponseBase) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAddresses() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetAddresses()))
        for i, v := range m.GetAddresses() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("addresses", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("closed_at", m.GetClosedAt())
        if err != nil {
            return err
        }
    }
    if m.GetContacts() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetContacts()))
        for i, v := range m.GetContacts() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("contacts", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("created_at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("customer_reference_id", m.GetCustomerReferenceId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("date_of_birth", m.GetDateOfBirth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("first_name", m.GetFirstName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("last_name", m.GetLastName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("metadata", m.GetMetadata())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("middle_name", m.GetMiddleName())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    if m.GetStatusReasons() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetStatusReasons()))
        for i, v := range m.GetStatusReasons() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("status_reasons", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("updated_at", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PersonResponseBase) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAddresses sets the addresses property value. Address information for the person. Note: This field is required for payouts, deposits, or account-to-account transfers.
func (m *PersonResponseBase) SetAddresses(value []PostalAddressResponseable)() {
    m.addresses = value
}
// SetClosedAt sets the closed_at property value. Timestamp when the status of the resource was set to "closed".
func (m *PersonResponseBase) SetClosedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.closed_at = value
}
// SetContacts sets the contacts property value. List of contact information for the person.
func (m *PersonResponseBase) SetContacts(value []ContactResponsePersonable)() {
    m.contacts = value
}
// SetCreatedAt sets the created_at property value. Timestamp when the resource was created.
func (m *PersonResponseBase) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetCustomerReferenceId sets the customer_reference_id property value. Unique reference id for the customer (business or person) resource. Generated by you.
func (m *PersonResponseBase) SetCustomerReferenceId(value *string)() {
    m.customer_reference_id = value
}
// SetDateOfBirth sets the date_of_birth property value. Date of birth in YYYY-MM-DD format. Note: This field is required for payouts, deposits, or account-to-account transfers. Age must be less than 100 years and greater than 18 years to be verified.
func (m *PersonResponseBase) SetDateOfBirth(value *string)() {
    m.date_of_birth = value
}
// SetFirstName sets the first_name property value. The first_name property
func (m *PersonResponseBase) SetFirstName(value *string)() {
    m.first_name = value
}
// SetId sets the id property value. Orum generated unique id for the resource.
func (m *PersonResponseBase) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetLastName sets the last_name property value. The last_name property
func (m *PersonResponseBase) SetLastName(value *string)() {
    m.last_name = value
}
// SetMetadata sets the metadata property value. Additional data you would like to provide on the resource. The field supports valid JSON of up to 5 key-value pairs with a maximum of 20 characters for the key and 50 characters for the value. Do not include any sensitive information.
func (m *PersonResponseBase) SetMetadata(value PersonResponseBase_metadataable)() {
    m.metadata = value
}
// SetMiddleName sets the middle_name property value. The middle_name property
func (m *PersonResponseBase) SetMiddleName(value *string)() {
    m.middle_name = value
}
// SetStatus sets the status property value. Status of person in Orum system.
func (m *PersonResponseBase) SetStatus(value *PersonStatus)() {
    m.status = value
}
// SetStatusReasons sets the status_reasons property value. Array that explains why the person failed verification.
func (m *PersonResponseBase) SetStatusReasons(value []PersonReasonCodeable)() {
    m.status_reasons = value
}
// SetUpdatedAt sets the updated_at property value. Timestamp when the resource was last updated.
func (m *PersonResponseBase) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updated_at = value
}
type PersonResponseBaseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAddresses()([]PostalAddressResponseable)
    GetClosedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetContacts()([]ContactResponsePersonable)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCustomerReferenceId()(*string)
    GetDateOfBirth()(*string)
    GetFirstName()(*string)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetLastName()(*string)
    GetMetadata()(PersonResponseBase_metadataable)
    GetMiddleName()(*string)
    GetStatus()(*PersonStatus)
    GetStatusReasons()([]PersonReasonCodeable)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    SetAddresses(value []PostalAddressResponseable)()
    SetClosedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetContacts(value []ContactResponsePersonable)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCustomerReferenceId(value *string)()
    SetDateOfBirth(value *string)()
    SetFirstName(value *string)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetLastName(value *string)()
    SetMetadata(value PersonResponseBase_metadataable)()
    SetMiddleName(value *string)()
    SetStatus(value *PersonStatus)()
    SetStatusReasons(value []PersonReasonCodeable)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
}
